"""Electronic-evidence support pack (Markdown): case manifest, integrity hashes, the hash-chained custody
trail, method statement, limitations and a DRAFT certificate template for a human signer.

This is support material. It does not certify admissibility and is not itself a certificate - a
responsible person must review it and sign. Confirm the currently prescribed certificate format under
Section 63 of the Bharatiya Sakshya Adhiniyam, 2023 with counsel before use."""
import datetime

import pii

ACTION_LABELS = {'analyze': 'Analyzed (original bytes and report hashed)', 'note': 'Analyst note added', 'assign': 'Case assigned',
                 'review': 'Review decision recorded', 'delete': 'Case deleted', 'landing_inspect': 'Landing page inspected (static, analyst-triggered)',
                 'gateway_hold': 'Held by the pre-delivery gateway', 'gateway_deliver': 'Delivered by the pre-delivery gateway',
                 'quarantine_release': 'Released from quarantine', 'quarantine_discard': 'Discarded from quarantine', 'blockchain_stamp': 'Chain head submitted for Bitcoin timestamp'}


def _when(epoch):
    try:
        return datetime.datetime.fromtimestamp(float(epoch), datetime.timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
    except (TypeError, ValueError, OSError):
        return 'unknown'


def _cell(value):
    return str(value if value not in (None, '') else '-').replace('|', '\\|').replace('\n', ' ')[:200]


def build(result, cid, events, chain, mask_emails=False):
    """result is the (possibly redacted/masked) report; events come from store.case_events; chain from store.verify."""
    findings = result.get('findings', [])
    rows = []
    for item in events:
        event = item['event']
        detail = ''
        if event.get('action') == 'note': detail = pii.sanitize(str(event.get('text', ''))[:120], mask_emails)
        elif event.get('action') == 'review': detail = f"{event.get('decision', '')}"
        elif event.get('action') == 'assign': detail = pii.sanitize(str(event.get('owner', '')), mask_emails)
        who = f" (by {event['actor']}, {event.get('role', '?')})" if event.get('actor') else ''
        rows.append(f"| {item['seq']} | {_when(event.get('at'))} | {ACTION_LABELS.get(event.get('action'), _cell(event.get('action')))}{_cell(who) if who else ''} | {_cell(detail)} | `{item['hash'][:16]}...` |")
    analyze = next((i['event'] for i in events if i['event'].get('action') == 'analyze'), {})
    lines = [
        '# Electronic evidence support pack - DRAFT',
        '',
        '> Support material generated by PRAHARI. **Not a certificate and not a finding of admissibility.** A responsible person must review, complete and sign the declaration in Part 5. Confirm the currently prescribed format under Section 63 of the Bharatiya Sakshya Adhiniyam, 2023 with counsel before use.',
        '',
        '## 1. Case manifest',
        f'- Case ID: `{cid}`',
        f"- Source: {_cell(result.get('source'))}",
        f"- Analyzed at: {_when(analyze.get('at') or result.get('created'))}",
        f"- Triage: {_cell((result.get('triage') or {}).get('label'))}; evidence score {result.get('score', '-')}/100 (heuristic, uncalibrated)",
        f"- Sender (as reported in headers): {_cell(result.get('sender'))}",
        f"- Subject: {_cell(result.get('subject'))}",
        f"- Export privacy: {'email addresses partially masked; ' if mask_emails else ''}Aadhaar/PAN/UPI/mobile numbers masked (best-effort, not certified DLP)",
        '',
        '## 2. Integrity hashes',
        '| Item | Algorithm | Value |',
        '|---|---|---|',
        f"| Original message bytes | SHA-256 | `{_cell(result.get('sha256'))}` |",
        f"| Stored analysis report | SHA-256 | `{_cell(analyze.get('report_hash'))}` |",
        '',
        'Recompute the first value with any SHA-256 tool over the original `.eml` file; it must match. The original bytes are retained unaltered in the evidence store and every derivative export is separate from them.',
        '',
        '## 3. Custody trail (hash-chained)',
        'Each event\'s hash covers the previous hash plus the event, so editing or removing an earlier event breaks every later hash.',
        '',
        '| Seq | Time | Action | Detail | Event hash |',
        '|---|---|---|---|---|',
        *(rows or ['| - | - | No events found for this case | - | - |']),
        '',
        f"Session chain verification at export time: **{'valid' if chain.get('valid') else 'NOT VALID - ' + _cell(chain.get('detail'))}** ({chain.get('checked', 0)} events checked; head `{_cell(chain.get('head'))}`).",
        f"Caveat: {_cell(chain.get('detail')) if chain.get('valid') else 'Investigate before relying on this pack.'}",
        'The chain head can additionally be anchored to the Bitcoin blockchain via OpenTimestamps (a separate, opt-in step). An anchor proves the head hash existed by a given time; it does not prove the email is genuine.',
        '',
        '## 4. Method and findings',
        '- Analysis is automated and static: header/authentication checks (SPF, DKIM, DMARC, ARC), content classification, link and attachment inspection, relay-path parsing. Nothing in the message was executed.',
        '- Locations and network data describe relay infrastructure, **not** the person who sent the email.',
        f"- {len(findings)} finding(s) recorded:",
        *(f"  - {_cell(f.get('title'))}: {_cell(f.get('detail'))}" for f in findings[:25]),
        '',
        '## 5. DRAFT declaration for a human signer',
        '*Structure only. To be completed and signed by the person in charge of the computer resource/system used, and by an expert where required.*',
        '',
        '| Field | To be completed |',
        '|---|---|',
        '| Name and designation of declarant | |',
        '| Organisation and system/device description (make, model, OS, software version) | |',
        '| Statement that the device/system was in lawful control and regularly used for the relevant activity | |',
        '| How the message was obtained and preserved (upload / mailbox export / push ingestion) | |',
        f"| Hash of original message (SHA-256) | `{_cell(result.get('sha256'))}` |",
        f"| Case ID for cross-reference | `{cid}` |",
        '| Declarant signature and date | |',
        '| Expert (if applicable): name, qualification, signature and date | |',
        '',
        '## 6. Limitations',
        '- This pack supports, but does not establish, admissibility; that depends on process, people and jurisdiction.',
        '- Local hash chaining is tamper-evident, not tamper-proof; full-chain rewriting or tail truncation may evade detection unless the head has been independently checkpointed or anchored.',
        '- Automated scores are heuristic and uncalibrated; treat them as review priority, not proof.',
    ]
    return '\n'.join(lines) + '\n'
