export default function PSAssessment({value}) {
  if(!value)return null
  return <section className="ps-section"><h2>Threat assessment</h2><p><strong>{value.categories.join(' · ')}</strong></p><p>{value.method}</p><p>{value.category_caveat}</p>
    {value.checks.map((c,i)=><div key={i}><strong>{c.title}</strong><p style={{overflowWrap:'anywhere'}}>{c.detail}</p></div>)}
    <details><summary>Origin assessment and inspection scope</summary><p>{value.origin_confidence}</p>{value.origin_evidence&&<><strong>Source evidence: {value.origin_evidence.confidence}</strong><p>Earliest reported public IP: {value.origin_evidence.earliest_reported_public_node?.ip||'Unavailable'} (not verified)</p>{value.origin_evidence.earliest_reliable_node&&<p>Receiver-attested ingress: {value.origin_evidence.earliest_reliable_node.ip} · {value.origin_evidence.earliest_reliable_node.receiver}</p>}<p>{value.origin_evidence.basis}</p><p>{value.origin_evidence.next_verification}</p></>}{value.origin_flags.map((f,i)=><p key={i}>{f}</p>)}<p>{value.attachment_scope}</p>{value.hosting_fingerprint&&<><strong>Hosting fingerprint: {value.hosting_fingerprint.status}</strong><p style={{overflowWrap:'anywhere'}}>{value.hosting_fingerprint.sha256||'Unavailable'}</p><p>{value.hosting_fingerprint.scope}</p></>}{value.identity_coverage&&<><strong>Protected identity directory: {value.identity_coverage.status}</strong><p>{value.identity_coverage.scope}</p></>}{value.infrastructure&&<><strong>Tor exit intelligence: {value.infrastructure.status}</strong><p>{value.infrastructure.matches.join(', ')||'No matched IPs available'}</p><p>{value.infrastructure.detail}</p></>}
    {value.ip_reputation&&value.ip_reputation.length>0&&<><strong>IP reputation (AbuseIPDB)</strong>{value.ip_reputation.map((r,i)=><p key={i} style={{overflowWrap:'anywhere'}}>{r.ip}: {r.status}{r.status==='available'?` · ${r.usage_type} · abuse score ${r.abuse_confidence_score} · Tor=${String(r.is_tor)}`:''} — {r.detail}</p>)}</>}
    {value.attachment_reputation&&value.attachment_reputation.length>0&&<><strong>Attachment reputation (VirusTotal)</strong>{value.attachment_reputation.map((r,i)=><p key={i} style={{overflowWrap:'anywhere'}}>{r.sha256.slice(0,16)}...: {r.status} — {r.detail}</p>)}</>}</details>
  </section>
}
